set nocompatible
filetype off


syntax on
set backspace=indent,eol,start
set hidden
set noswapfile
"set nobackup
"set undodir=~/.vim/undodir
"set undofile
set nu

let $RTP=split(&runtimepath, ',')[0]
let $RC="$HOME/.vim/vimrc"

set path=.,**
"copies to System clipboard
set clipboard=unnamed


call plug#begin('~/.vim/plugged')

Plug 'itchyny/lightline.vim'
"Plug 'vimfm/vimfm.vim'

" LaTex plugins
Plug 'lervag/vimtex'

let g:tex_flavor='latex'
let g:vimtex_view_method='zathura'
let g:vimtex_quickfix_mode=0
set conceallevel=1
let g:tex_conceal='abdmg'

Plug 'sirver/ultisnips'
let g:UltiSnipsExpandTrigger = '<tab>'
let g:UltiSnipsJumpForwardTrigger = '<tab>'
let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'
" LaTex plugins

call plug#end()

filetype plugin indent on
