
let $RTP=split(&runtimepath, ',')[0]
let $RC="$HOME/.vim/vimrc"

set path=.,**
"copies to System clipboard
set clipboard=unnamed
let mapleader = "<space>"


call plug#begin('~/.vim/plugged')

Plug 'morhetz/gruvbox'
Plug 'mbbill/undotree'
"Plug 'git@github.com:Valloric/YouCompleteMe.git'

Plug 'itchyny/lightline.vim'
"Plug 'vimfm/vimfm.vim'

" LaTex plugins
Plug 'lervag/vimtex'

let g:tex_flavor='latex'
let g:vimtex_compiler_latexmk = {}
let g:vimtex_compiler_latexmk.continuous = 1
let g:vimtex_compiler_latexmk.callback = 1
let g:vimtex_compiler_latexmk.background = 1
" let g:vimtex_compiler_latexmk.backend = 'jobs'

if has('nvim')
  let g:vimtex_quickfix_latexlog = {'fix_paths':0}
  let g:vimtex_compiler_progname = 'nvr'
endif

let g:vimtex_view_method='zathura'
let g:vimtex_quickfix_mode=0
set conceallevel=1
let g:tex_conceal='abdmg'

"code completion
if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif
let g:deoplete#enable_at_startup = 1
"call deoplete#custom#option('smart_case', v:true
" deoplete tab-complete
inoremap <expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"
nnoremap <c-x> :w<cr>

"code completion, crashes in Python
"Plug 'roxma/nvim-completion-manager'

"Plug 'nvim-lua/completion-nvim'

"Plug 'sirver/ultisnips'
"let g:UltiSnipsExpandTrigger = '<tab>'
"let g:UltiSnipsJumpForwardTrigger = '<tab>'
"let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'

"error in snippets :(
"let g:UltiSnipsSnippetDirectories=["UltiSnips", "my_snippets"]

" LaTex plugins

call plug#end()

let mapleader = " "

set nocompatible
filetype off


syntax on
set noerrorbells
set backspace=indent,eol,start
set hidden
set noswapfile
set nobackup

set undodir=~/.vim/undodir
set undofile
set nu relativenumber

set wildmode=longest,list,full

colorscheme gruvbox
set background=dark

filetype plugin indent on

autocmd BufWritePre * %s/\s\+$//e
